#!/bin/bash
# swarm-launcher.sh
# Auto-generated by code-harness for task T009: Add rate limiting to all public endpoints
# Each sub-task runs as an independent headless Claude Code session.
#
# Usage:
#   ./swarm-launcher.sh                     # single account
#   MULTI_ACCOUNT=1 ./swarm-launcher.sh     # rotate across multiple accounts
#
# Multi-account mode reads API keys from .harness/.api-keys (one per line, gitignored)

set -e

ENDPOINTS=(
  "src/api/routes/users.py"
  "src/api/routes/posts.py"
  "src/api/routes/comments.py"
  "src/api/routes/auth.py"
  "src/api/routes/search.py"
  "src/api/routes/upload.py"
  "src/api/routes/settings.py"
  "src/api/routes/feed.py"
  "src/api/routes/notifications.py"
  "src/api/routes/tags.py"
  "src/api/routes/categories.py"
  "src/api/routes/bookmarks.py"
  "src/api/routes/reactions.py"
  "src/api/routes/reports.py"
  "src/api/routes/export.py"
)

# Load API keys for multi-account rotation
KEYS=()
if [ "$MULTI_ACCOUNT" = "1" ] && [ -f .harness/.api-keys ]; then
  while IFS= read -r key; do
    [ -n "$key" ] && KEYS+=("$key")
  done < .harness/.api-keys
  echo "Multi-account mode: ${#KEYS[@]} accounts loaded"
fi

MAX_PARALLEL=${MAX_PARALLEL:-5}  # limit concurrent sessions
RUNNING=0
TOTAL=${#ENDPOINTS[@]}
COMPLETED=0

echo "Starting swarm: $TOTAL tasks, max $MAX_PARALLEL parallel"
echo ""

for i in "${!ENDPOINTS[@]}"; do
  endpoint="${ENDPOINTS[$i]}"
  name=$(basename "$endpoint" .py)
  
  # Wait if at max parallelism
  while [ $RUNNING -ge $MAX_PARALLEL ]; do
    wait -n 2>/dev/null || true
    RUNNING=$((RUNNING - 1))
    COMPLETED=$((COMPLETED + 1))
    echo "[$COMPLETED/$TOTAL] A task completed. Running: $RUNNING"
  done
  
  # Build the command
  PROMPT="Add rate limiting to all public endpoints in $endpoint. \
Use the project's existing rate limiting middleware. \
Follow standards in .claude/rules/api-quality.md. \
After implementation, run: pnpm test -- --grep '$(basename $endpoint .py)' \
to verify. Do not modify any other files."
  
  CMD="claude -p \"$PROMPT\" --bare --allowedTools \"Read,Edit,Write,Bash,Grep,Glob\""
  
  # Multi-account rotation
  if [ ${#KEYS[@]} -gt 0 ]; then
    key_index=$((i % ${#KEYS[@]}))
    CMD="ANTHROPIC_API_KEY=\"${KEYS[$key_index]}\" $CMD"
  fi
  
  echo "[start] $name (task $((i+1))/$TOTAL)"
  eval "$CMD" > ".harness/swarm-logs/$name.log" 2>&1 &
  
  RUNNING=$((RUNNING + 1))
done

# Wait for remaining
wait
echo ""
echo "Swarm complete. $TOTAL tasks finished."
echo "Logs in .harness/swarm-logs/"
echo ""
echo "Next: run an integration check session to verify consistency:"
echo "  claude -p 'Check all rate limiting implementations for consistency across src/api/routes/'"
